spring:
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://service-registry:8070/eureka/

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
    enabled-by-default: true